/* Generated By:JavaCC: Do not edit this line. OutputJSTreeConstants.java Version 5.0 */
package com.js2pv.too;

public interface OutputJSTreeConstants
{
  public int JJTSTART = 0;
  public int JJTPROCESS = 1;
  public int JJTEXP = 2;
  public int JJTFUNBLOCK = 3;
  public int JJTNEWOBJECT = 4;
  public int JJTUSEFUN = 5;
  public int JJTNEWSEND = 6;
  public int JJTNOMEAT = 7;
  public int JJTYINWORD = 8;
  public int JJTYINWORDPOINT = 9;
  public int JJTEXPSTUB = 10;
  public int JJTDIGITSUB = 11;
  public int JJTVARSUB = 12;
  public int JJTNEWDEFINE = 13;
  public int JJTNEWDEFINELET = 14;
  public int JJTNEWDEFINEIN = 15;
  public int JJTDEFINEEIF = 16;
  public int JJTDEFINEMAOHAO = 17;
  public int JJTDEFINEETHEN = 18;
  public int JJTDEFINEEELSE = 19;
  public int JJTDEFINEEELOR = 20;
  public int JJTDEFINEAND = 21;
  public int JJTDEFINEFUNCTION = 22;
  public int JJTDEFINEDENGYU = 23;
  public int JJTDEFINEEQUAL = 24;
  public int JJTDEFINENULL = 25;
  public int JJTDEFINENOTEQUAL = 26;
  public int JJTDEFINEBIGGER = 27;
  public int JJTDEFINESMALLER = 28;
  public int JJTDEFINEOBRACE = 29;
  public int JJTDEFINECBARCE = 30;
  public int JJTDEFINENEW = 31;
  public int JJTDEFINEYINHAO = 32;
  public int JJTDEFINEPOINT = 33;
  public int JJTDEFINELP = 34;
  public int JJTDEFINERP = 35;
  public int JJTDEFINECOMMA = 36;


  public String[] jjtNodeName = {
    "Start",
    "process",
    "exp",
    "funblock",
    "newobject",
    "usefun",
    "newsend",
    "nomeat",
    "yinword",
    "yinwordpoint",
    "expstub",
    "digitsub",
    "varsub",
    "newdefine",
    "newdefinelet",
    "newdefinein",
    "defineeif",
    "definemaohao",
    "defineethen",
    "defineeelse",
    "defineeelor",
    "defineand",
    "definefunction",
    "definedengyu",
    "defineequal",
    "definenull",
    "definenotequal",
    "definebigger",
    "definesmaller",
    "defineOBRACE",
    "defineCBARCE",
    "defineNEW",
    "defineyinhao",
    "definepoint",
    "defineLP",
    "defineRP",
    "defineCOMMA",
  };
}
/* JavaCC - OriginalChecksum=3c218731da708880407ccef2453d3b87 (do not edit this line) */
