/* Generated By:JavaCC: Do not edit this line. OutputJSVisitor.java Version 5.0 */
package com.js2pv.too;

public interface OutputJSVisitor
{
  public Object visit(SimpleNode node, Object data);
}
/* JavaCC - OriginalChecksum=b81fc618afdf2df504dd6e8a26dcf7f5 (do not edit this line) */
